title: "Praxis Dama"
author: "Myself!"
description: "Berlin Charl"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "univpncisco.pdf", title: CV, icon: home}
  - {file: "README.md"}
  - {title: "DoctoLib", url: "https://www.doctolib.de/innere-und-allgemeinmediziner/berlin/lars-christian-baumeister?insurance_sector=public"}
  - {title: "Location", url: "https://www.google.com/maps/place/Vivantes+Wenckebach-Klinikum/@52.4586588,13.387481,16.79z/data=!4m5!3m4!1s0x47a84ff86ab59733:0x4b0c3152407cfa05!8m2!3d52.4589186!4d13.3879962"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:antonkraus@users.noreply.github.com"}
  - {title: Github, icon: github, url: "https://github.com/antonkraus"}
  - {title: Contact, icon: Contact, url: "https://github.com"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
